### ISSUE TITLE
UI Scaling Bug in “Chat” Tab After Window Resize on High-Res Display

### ISSUE THREAD

**Issue by HM-obs** [lmstudio-ai/lmstudio-bug-tracker#1196]
Which version of LM Studio?
LM Studio 0.3.31 (Build 7)

Which operating system?
Windows 11
What is the bug?
On a single high-resolution monitor (2560×1600), LM Studio initially displays correctly. However, when the active tab is “Chat” and the application window is moved, resized, or maximized/minimized, the UI suddenly scales up excessively. Text and interface elements become disproportionately large, making the application difficult to use. This issue does not occur in the “Developer” or “My Models” tabs.
Once the scaling issue appears, it persists across the app. However, switching to “Developer” or “My Models” and then maximizing the window restores the correct scaling. Returning to “Chat” reintroduces the problem, which can again be reversed by switching tabs.

Screenshots

<img width="2559" height="1538" alt="Image" src="https://github.com/user-attachments/assets/822eb55c-7658-4384-bf5b-4cca4a63d638" />

<img width="2559" height="1530" alt="Image" src="https://github.com/user-attachments/assets/51ef4c2b-8620-4573-814a-e5dce3f7a2aa" />

<img width="2555" height="1534" alt="Image" src="https://github.com/user-attachments/assets/b83cbe34-26eb-4800-9e07-0c35a79dc596" />

<img width="2558" height="1540" alt="Image" src="https://github.com/user-attachments/assets/f613cfde-8adc-4510-99d9-f2b132972e76" />

Logs
(No crash logs observed, as the application continues to run normally. Add logs if available.)

To Reproduce
- Launch LM Studio on a monitor with 2560×1600 resolution
- Navigate to the “Chat” tab
- Move, resize, or maximize/minimize the application window
- Observe the oversized UI scaling
- Switch to “Developer” or “My Models” tab
- Maximize the window again → scaling returns to normal
- Switch back to “Chat” → scaling issue reappears

**Comment by kl33list** [comment]
The same problem

**Comment by gray0072** [comment]
The same for me. Very annoying. 
3840x2400, 250% scale.
I tried all combinations from Windows compatibility "High DPI settings" - no result.
The top menu looks ugly:
<img width="2059" height="152" alt="Image" src="https://github.com/user-attachments/assets/037c2088-8aba-46e0-a196-6ffc82e14143" />

**Comment by gray0072** [comment]
For me the issue was solved by downloading the latest version (0.3.39) from the [official site](https://lmstudio.ai/download) and installing it to the same folder as before.
During installation, the "restore" option was missing, but after installation, all models and chats remained in their places.

**Comment by HM-obs** [comment]
> Issue was solved by downloading the latest version (0.3.39) from the [official site](https://lmstudio.ai/download) and installing it to the same folder as before. During installation, the "restore" option was missing, but after installation, all models and chats remained in their places.

Thank you for the update. However, I unfortunately still have the exact same issue. I reinstalled LM studio as instructed from the official site.

Issue thus is **not resolved**, as far as I am concerned

**Comment by kl33list** [comment]
the update didn't work

**Comment by bhehe** [comment]
Same here, running 0.3.39 and having the issue. I've tried the Windows compatibility settings tweaks for high resolution, no luck there either. It's basically made LM Studio extremely difficult to use, surprised there's not more mention or discussion of it here.

I'm on a 5k x 2k monitor with the laptop monitor still active and attached so I think that's complicating the matter perhaps.

**Comment by gray0072** [comment]
Another potential solution is to press **Ctrl + 0** (zero). It forces LM Studio to re-render to 100% scale.
It helped me and surprisingly it works even after app restart.

**Comment by kl33list** [comment]
Ctrl + 0 (zero)
it worked

**Comment by HM-obs** [comment]
> Another potential solution is to press **Ctrl + 0** (zero). It forces LM Studio to re-render to 100% scale. It helped me and surprisingly it works even after app restart.

this solution worked for me as well, thank you!
