### ISSUE TITLE
LM Studio closes stream pipeline after 5 minutes into a task

### ISSUE THREAD

**Issue by petref** [lmstudio-ai/lmstudio-bug-tracker#1254]
Given a more complex task the stream pipeline closes at 5 minutes into the job as seen in the output pasted below

callLMStudioWithRetry(...); }\n"} | 18:33:31.322 |  
-- | -- | -- | --
  | heartbeat | { "keepalive": true } | 18:33:36.430 |  
  | heartbeat | { "keepalive": true } | 18:33:51.434 |  
  | heartbeat | { "keepalive": true } | 18:34:06.438 |  
  | heartbeat | { "keepalive": true } | 18:34:21.447 |  
  | heartbeat | { "keepalive": true } | 18:34:36.456 |  
  | heartbeat | { "keepalive": true } | 18:34:51.468 |  
  | heartbeat | { "keepalive": true } | 18:35:06.475 |  
  | heartbeat | { "keepalive": true } | 18:35:21.484 |  
  | heartbeat | { "keepalive": true } | 18:35:36.493 |  
  | heartbeat | { "keepalive": true } | 18:35:51.502 |  
  | heartbeat | { "keepalive": true } | 18:36:06.503 |  
  | heartbeat | { "keepalive": true } | 18:36:21.514 |  
  | heartbeat | { "keepalive": true } | 18:36:36.530 |  
  | heartbeat | { "keepalive": true } | 18:36:51.540 |  
  | heartbeat | { "keepalive": true } | 18:37:06.548 |  
  | heartbeat | { "keepalive": true } | 18:37:21.559 |  
  | heartbeat | { "keepalive": true } | 18:37:36.566 |  
  | heartbeat | { "keepalive": true } | 18:37:51.567 |  
  | heartbeat | { "keepalive": true } | 18:38:06.568 |  
  | heartbeat | { "keepalive": true } | 18:38:21.575 |  
  | error | {"message":"terminated"} | 18:38:34.315 |  
  |   |   |   |  
The job was to read a file longer then the usual 2 minutes read, on an AMD Radeon with Ryzen 7000s, given not everybody has advanced Intel With a lot of GPU on their hands this limit seems to be hardcoded and in someway unproductive... since I didn't find it anywhere specified ... please shake the hand of the briliant mind who thought of this torture instrument.. A+ Hardcoder Developer

**Comment by petref** [comment]
Fixed with https://github.com/nodejs/undici/pull/1870/commits/8f16b859066b2542eaef4162ca1e83808796a960

Srry 🥇

**Comment by parthpat12** [comment]
This is still happening. Has this been merged? Running latest beta: LM Studio 0.4.0 (Build 13)

**Comment by petref** [comment]
The issue is comming from node not the LM-Studio, requests have timeouts to an default of 5 minutes and of course if you use unidici same there setTimeout needs to be extended as default is 5 minutes both of them .. From my side the issue is closed

 bodyTimeout: 300_000,
        headersTimeout: 300_000,
