### ISSUE TITLE
LM Studio 0.3.3 RAG issue with PDF Attachment

### ISSUE THREAD

**Issue by hokie911** [lmstudio-ai/lmstudio-bug-tracker#140]
I have noticed issue with the LM Studio 0.3.3 version when uploading a PDF, such as the NIST SP 800-53r5.pdf. The Assistant shows LM Studio attempting to process it, and it always get stuck at 1% and never completes.

I am running LM Studio on a M2 Max Macbook system with over 48GB of Unified Memory.
<img width="810" alt="image" src="https://github.com/user-attachments/assets/9740bf26-7bb6-43e8-b2fd-3430c84ff846">

**Comment by yagil** [comment]
Should be fixed in https://lmstudio.ai/download

**Comment by fahrularfandimn** [comment]
I think the issue still persists in version 0.3.4

![image](https://github.com/user-attachments/assets/99618300-fee7-46fa-8f67-8918822d8f39)

**Comment by yagil** [comment]
@fahrularfandimn does it stay stuck at 42%?

In this case, how many pages is the PDF, and what is the context window size you’ve set?

**Comment by fahrularfandimn** [comment]
Yes, it is. The PDF has 2 pages and the context length is 22,222 tokens. That day, I tried several documents and the result was still the same, but today I tested it again and it worked well. I don't know why, I did not change anything in the LM Studio settings.
