### ISSUE TITLE
Multi-GPU Setup Does not Shows in Advance Settings (Right Sidebar)

### ISSUE THREAD

**Issue by gchriswill** [lmstudio-ai/lmstudio-bug-tracker#194]
I'm trying to get configured a 6x GPU setup for offloading across available GPUs, but I can't see anywhere on the app any option for selecting GPUs nor multi-GPU options. I noticed that LMS 0.3.5 has detected all the GPUs at the Hardware Info > GPUs section at System Resources of the App Settings, and I can also see all the VRAM combined 72GB (6 * GPU-12GB-VRAM) at Memory Capacity section with the Vulkan engine selected, but there are not any multi-GPU configuration options over there.

---

![Screenshot 2024-11-10 125837](https://github.com/user-attachments/assets/197af292-5f49-4be6-8b2d-31a44b1b1880)

---

In previous versions of LMS, we were able to see the GPU preferences pane in Advance Settings (Right sidebar), but I took a long time off, and when returned back to my tinkering with LMS and my setup, I decided to upgrade to the latest version (0.3.5), and I can't find any multi-GPU options anymore. So, even furthermore, during my research my GPUs gets VRAM consumed when loading very large models, and their utilization and memory clock speeds get a boost/peak at the inference time. 

So, the big question I have, does this means that the resource distribution is handled automatically by LMS, and there is no need for LMS's Users/developers to manage offloading across multiple GPUs anymore? 

💭 
🤔 

---

**Hardware:**

OS: Windows 11 (23H2)
CPU: Intel Core i3-10100
RAM: Crucial PRO 32GB
Storage: Crucial BX SATA SSD 250 GB
GPUs: 6x - AMD XFX Merc RX6700XT

**Comment by jortfal** [comment]
Hi!

I can understand that the distribution of resources is automatically managed by LM Studio.

But I think it is necessary to be able to select on which GPU to load the model and run it.

I just connected a second GPU to my PC.  It is an 8GB Asus 3070Ti to my PC for use with my monitors and my system in general. Since I have a 24GB Nvidia RTX 3090 that I want to use exclusively with LM Studio.

Is it possible to somehow tell LM Studio to only use one GPU? If not currently possible, will it be possible in the next version of LM Studio?

Translated with DeepL.com (free version)

**Comment by Tsubajashi** [comment]
Same here, would love to be able to pick just one gpu out of my 2 4090s to run LM Studio on, especially with its server capabilities.

**Comment by mpieck** [comment]
Manual GPU selection in multi GPU configs is a must have. For rigs with different GPUs, ex 4090 AND 4060Ti currently LMStudio distributes the model using all avaliable GPUs, even when the model first into VRAM of the faster card. So with a small model using both 4090 and 4060Ti the performance will be degraded to the speed of slower card. User should have posibility to select GPU for a model in multi-GPU configurations!

**Comment by mpieck** [comment]
Manual GPU selection in multi GPU configs is a must have. For rigs with different GPUs, ex 4090 AND 4060Ti currently LMStudio distributes the model using all avaliable GPUs, even when the model first into VRAM of the faster card. So with a small model using both 4090 and 4060Ti the performance will be degraded to the speed of slower card. User should have posibility to select GPU for a model in multi-GPU configurations!

**Comment by ralfstrobel** [comment]
You can go into the NVIDIA driver settings and define which GPUs are available for CUDA (globally or per application), which will force LM Studio to use only those cards. But yes, that is quite the annoying workaround, especially if you often want to switch between different size models.

**Comment by mpieck** [comment]
>> You can go into the NVIDIA driver settings and define which GPUs are available for CUDA

LMStudio is not the only software I'm using for AI. I cannot dissable GPU in the driver settings. Moreover this workaround is not suitable if I want to server on LMStudio many models on different GPUs each. LMStudio is using llama.cpp for runtime, with this library in multi-GPU env it is possible to select 1 GPU for the whole model.

**Comment by rik43** [comment]
same problem, I'd like to use only 1 or 2 of mine gpu

**Comment by yagil** [comment]
@rik43 

which version are you on? 

Can you please share a screenshot of Ctrl + Shift + H?

**Comment by mpieck** [comment]
![Image](https://github.com/user-attachments/assets/7cabbeb3-5cb5-429b-ba86-9b2315ef1748)

@yagil  I'm on 0.3.9 Build 5. I want to select only 1 GPU per model to load it. In the past it was possible, now it is not.

**Comment by rik43** [comment]
0.3.9 Build 6. 
![Image](https://github.com/user-attachments/assets/d11351d2-042f-44f9-873f-49e8ae9aff95)

if i select any sumple model (like a 14-17gb) it loads to all gpus, and flux (running on gpu:2) is fail.

**Comment by yagil** [comment]
Thanks @mpieck — in the past, how did you select which GPU to use?

**Comment by shabadabadoo** [comment]
I'll add to this that prior to version 0.3.9 build 6, both my GPUs were automatically used. After updating, I had to delete all my runtimes to get any model to work again, and only one GPU is being used.

I still have the installer for 0.3.6, so I can try that tomorrow to see if there is any change.

**Comment by Amarillys** [comment]
I successfully implemented switching to using only Intel's integrated graphics card on a machine with both an Nvidia GPU and an Intel integrated graphics card, while the default is to use the Nvidia GPU. The method was setting up the graphics settings in Windows (11) ' setting panel, to prioritize the integrated Intel card.

**Comment by yukeyuan** [comment]
Being able to select which gpus to load the model in a multi-gpu environment is a must-have. Any updates from the devs?

**Comment by jortfal** [comment]
It has been 3 months since this issue was opened. 
We really need some news from the developers.

**Comment by Tsubajashi** [comment]
Yea, any kind of news would be cool to have about that.

**Comment by simeononsecurity** [comment]
Can confirm this issue is still on latest as of today.

**Comment by xxakirhaxx** [comment]
How has this not been worked on? Guess I'm dropping LM studio. Wanted to use it for coding, but without this key feature, it's impossible with my set up, well not impossible, but sure as well creates a lot of extra steps that could be fixed with a detection that's already there and a check box.

**Comment by jortfal** [comment]
Hello,

This is already solved. You just need to update LM Studio.

By accessing the ‘App Settings’ menu, in the left menu, under ‘Hardware’ you can configure the ‘Allocation Strategy’ and mark which GPUs to use.

![Image](https://github.com/user-attachments/assets/52c14f75-d528-486c-93b1-08af35b5c955)

@gchriswill this issue can now be closed :)

Best regards!

**Comment by ralfstrobel** [comment]
To be precise, this seems to be part of 0.3.14, which is currently still in beta.

**Comment by mpieck2** [comment]
> This is already solved. You just need to update LM Studio.

No, it is not solved. This setting is per LMStudio instance (which is a small step forward), but you still cannot choose GPU per loaded model basis.

**Comment by gchriswill** [comment]
Bump! 

Any update on multi-gpu configuration?  

Scenario: 

> I have 4 GPUs, and I want to use 2 GPUs only for loading the model for those 2 GPUs specifically, and not the 4 GPUs.

**Comment by gchriswill** [comment]
> Hello,
> 
> This is already solved. You just need to update LM Studio.
> 
> By accessing the ‘App Settings’ menu, in the left menu, under ‘Hardware’ you can configure the ‘Allocation Strategy’ and mark which GPUs to use.
> 
> ![Image](https://github.com/user-attachments/assets/52c14f75-d528-486c-93b1-08af35b5c955)
> 
> [@gchriswill](https://github.com/gchriswill) this issue can now be closed :)
> 
> Best regards!

@jortfal What about AMD GPUs?

**Comment by yagil** [comment]
Thanks for your interest in this. This is a very old issue so it’s unclear what the ask is. Can you please open a fresh issue with the specific request? Thank you, going to close this one

**Comment by gchriswill** [comment]
@yagil I found the purpose for closure and determination to close this issue very very weird and odd. This issue is very very clear, look all the comments and inquiries it has resembling and echoing the same concern. Even on discord channel for the matching post. https://discord.com/channels/1110598183144399058/1305297268940738672 

Literally, the feature was removed, and we are trying to bring the necessary information to the team that that multi-gpu allocation configuration PER MODEL is crucial, and a must have specially for setups running full models and/or for multi-model scenarios.

**Comment by yagil** [comment]
> [@yagil](https://github.com/yagil) I found the purpose for closure and determination to close this issue very very weird and odd. This issue is very very clear, look all the comments and inquiries it has resembling and echoing the same concern. Even on discord channel for the matching post. https://discord.com/channels/1110598183144399058/1305297268940738672
> 
> Literally, the feature was removed, and we are trying to bring the necessary information to the team that that multi-gpu allocation configuration PER MODEL is crucial, and a must have specially for setups running full models and/or for multi-model scenarios.

I invited you to open a fresh issue. This will make it easier for the team to understand your current request. I think that's not unusual, and it will help your goals as well.

The original issue is from 2024 and most details aren't applicable anymore.
